/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoardOfDirectorsRouteImport } from './routes/board-of-directors'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ScientistsRouteRouteImport } from './routes/scientists/route'
import { Route as PartnershipsRouteRouteImport } from './routes/partnerships/route'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScientistsIndexRouteImport } from './routes/scientists/index'
import { Route as PartnershipsIndexRouteImport } from './routes/partnerships/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ScientistsSlugRouteImport } from './routes/scientists/$slug'
import { Route as PartnershipsSponsorshipRouteImport } from './routes/partnerships/sponsorship'
import { Route as EventsSlugRouteRouteImport } from './routes/events/$slug/route'
import { Route as EventsSlugIndexRouteImport } from './routes/events/$slug/index'
import { Route as EventsSlugPriorityListRouteImport } from './routes/events/$slug/priority-list'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardOfDirectorsRoute = BoardOfDirectorsRouteImport.update({
  id: '/board-of-directors',
  path: '/board-of-directors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ScientistsRouteRoute = ScientistsRouteRouteImport.update({
  id: '/scientists',
  path: '/scientists',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRouteRoute = PartnershipsRouteRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScientistsIndexRoute = ScientistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScientistsRouteRoute,
} as any)
const PartnershipsIndexRoute = PartnershipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnershipsRouteRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const ScientistsSlugRoute = ScientistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScientistsRouteRoute,
} as any)
const PartnershipsSponsorshipRoute = PartnershipsSponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => PartnershipsRouteRoute,
} as any)
const EventsSlugRouteRoute = EventsSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRouteRoute,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsSlugRouteRoute,
} as any)
const EventsSlugPriorityListRoute = EventsSlugPriorityListRouteImport.update({
  id: '/priority-list',
  path: '/priority-list',
  getParentRoute: () => EventsSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/partnerships': typeof PartnershipsRouteRouteWithChildren
  '/scientists': typeof ScientistsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/$slug': typeof EventsSlugRouteRouteWithChildren
  '/partnerships/sponsorship': typeof PartnershipsSponsorshipRoute
  '/scientists/$slug': typeof ScientistsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/scientists/': typeof ScientistsIndexRoute
  '/events/$slug/priority-list': typeof EventsSlugPriorityListRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/partnerships/sponsorship': typeof PartnershipsSponsorshipRoute
  '/scientists/$slug': typeof ScientistsSlugRoute
  '/events': typeof EventsIndexRoute
  '/partnerships': typeof PartnershipsIndexRoute
  '/scientists': typeof ScientistsIndexRoute
  '/events/$slug/priority-list': typeof EventsSlugPriorityListRoute
  '/events/$slug': typeof EventsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/partnerships': typeof PartnershipsRouteRouteWithChildren
  '/scientists': typeof ScientistsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/events/$slug': typeof EventsSlugRouteRouteWithChildren
  '/partnerships/sponsorship': typeof PartnershipsSponsorshipRoute
  '/scientists/$slug': typeof ScientistsSlugRoute
  '/events/': typeof EventsIndexRoute
  '/partnerships/': typeof PartnershipsIndexRoute
  '/scientists/': typeof ScientistsIndexRoute
  '/events/$slug/priority-list': typeof EventsSlugPriorityListRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/partnerships'
    | '/scientists'
    | '/about'
    | '/board-of-directors'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/resources'
    | '/sitemap.xml'
    | '/events/$slug'
    | '/partnerships/sponsorship'
    | '/scientists/$slug'
    | '/events/'
    | '/partnerships/'
    | '/scientists/'
    | '/events/$slug/priority-list'
    | '/events/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board-of-directors'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/resources'
    | '/sitemap.xml'
    | '/partnerships/sponsorship'
    | '/scientists/$slug'
    | '/events'
    | '/partnerships'
    | '/scientists'
    | '/events/$slug/priority-list'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/partnerships'
    | '/scientists'
    | '/about'
    | '/board-of-directors'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/news'
    | '/privacy'
    | '/programs'
    | '/resources'
    | '/sitemap.xml'
    | '/events/$slug'
    | '/partnerships/sponsorship'
    | '/scientists/$slug'
    | '/events/'
    | '/partnerships/'
    | '/scientists/'
    | '/events/$slug/priority-list'
    | '/events/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  PartnershipsRouteRoute: typeof PartnershipsRouteRouteWithChildren
  ScientistsRouteRoute: typeof ScientistsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BoardOfDirectorsRoute: typeof BoardOfDirectorsRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-of-directors': {
      id: '/board-of-directors'
      path: '/board-of-directors'
      fullPath: '/board-of-directors'
      preLoaderRoute: typeof BoardOfDirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scientists': {
      id: '/scientists'
      path: '/scientists'
      fullPath: '/scientists'
      preLoaderRoute: typeof ScientistsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scientists/': {
      id: '/scientists/'
      path: '/'
      fullPath: '/scientists/'
      preLoaderRoute: typeof ScientistsIndexRouteImport
      parentRoute: typeof ScientistsRouteRoute
    }
    '/partnerships/': {
      id: '/partnerships/'
      path: '/'
      fullPath: '/partnerships/'
      preLoaderRoute: typeof PartnershipsIndexRouteImport
      parentRoute: typeof PartnershipsRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/scientists/$slug': {
      id: '/scientists/$slug'
      path: '/$slug'
      fullPath: '/scientists/$slug'
      preLoaderRoute: typeof ScientistsSlugRouteImport
      parentRoute: typeof ScientistsRouteRoute
    }
    '/partnerships/sponsorship': {
      id: '/partnerships/sponsorship'
      path: '/sponsorship'
      fullPath: '/partnerships/sponsorship'
      preLoaderRoute: typeof PartnershipsSponsorshipRouteImport
      parentRoute: typeof PartnershipsRouteRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof EventsSlugRouteRoute
    }
    '/events/$slug/priority-list': {
      id: '/events/$slug/priority-list'
      path: '/priority-list'
      fullPath: '/events/$slug/priority-list'
      preLoaderRoute: typeof EventsSlugPriorityListRouteImport
      parentRoute: typeof EventsSlugRouteRoute
    }
  }
}

interface EventsSlugRouteRouteChildren {
  EventsSlugPriorityListRoute: typeof EventsSlugPriorityListRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

const EventsSlugRouteRouteChildren: EventsSlugRouteRouteChildren = {
  EventsSlugPriorityListRoute: EventsSlugPriorityListRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}

const EventsSlugRouteRouteWithChildren = EventsSlugRouteRoute._addFileChildren(
  EventsSlugRouteRouteChildren,
)

interface EventsRouteRouteChildren {
  EventsSlugRouteRoute: typeof EventsSlugRouteRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsSlugRouteRoute: EventsSlugRouteRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

interface PartnershipsRouteRouteChildren {
  PartnershipsSponsorshipRoute: typeof PartnershipsSponsorshipRoute
  PartnershipsIndexRoute: typeof PartnershipsIndexRoute
}

const PartnershipsRouteRouteChildren: PartnershipsRouteRouteChildren = {
  PartnershipsSponsorshipRoute: PartnershipsSponsorshipRoute,
  PartnershipsIndexRoute: PartnershipsIndexRoute,
}

const PartnershipsRouteRouteWithChildren =
  PartnershipsRouteRoute._addFileChildren(PartnershipsRouteRouteChildren)

interface ScientistsRouteRouteChildren {
  ScientistsSlugRoute: typeof ScientistsSlugRoute
  ScientistsIndexRoute: typeof ScientistsIndexRoute
}

const ScientistsRouteRouteChildren: ScientistsRouteRouteChildren = {
  ScientistsSlugRoute: ScientistsSlugRoute,
  ScientistsIndexRoute: ScientistsIndexRoute,
}

const ScientistsRouteRouteWithChildren = ScientistsRouteRoute._addFileChildren(
  ScientistsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  PartnershipsRouteRoute: PartnershipsRouteRouteWithChildren,
  ScientistsRouteRoute: ScientistsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BoardOfDirectorsRoute: BoardOfDirectorsRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
